# Generated by Django 5.2.7 on 2025-11-05 16:32

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='About Blog')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, unique=True)),
                ('body', models.TextField(verbose_name='ARticle body')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article viewer',
                'verbose_name_plural': 'Article viewer',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Carousel number')),
                ('title', models.CharField(blank=True, help_text='Carousel title', max_length=20, null=True)),
                ('content', models.TextField(blank=True, max_length=80, null=True)),
                ('img_url', models.CharField(blank=True, help_text='Image URL', max_length=200, null=True)),
                ('url', models.CharField(blank=True, help_text='URL', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
                'ordering': ['number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Description of the category SEO', max_length=240)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FeedHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.TextField(help_text='You can fill in a base64 image or an icon URL.')),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(blank=True, help_text='Define task to collect data', null=True)),
                ('sort_order', models.IntegerField(default=99)),
            ],
            options={
                'verbose_name': 'Feed Hub',
                'verbose_name_plural': 'Feed Hub',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Sites Logo')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=False)),
                ('not_show_reason', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Friend Link',
                'verbose_name_plural': 'Friend Link',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For example: GitHub home page', max_length=20, unique=True)),
                ('icon', models.CharField(help_text='For example: fa-github', max_length=20, unique=True)),
                ('link', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=99)),
            ],
            options={
                'verbose_name': 'Menu external link',
                'verbose_name_plural': 'Menu external link',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.IntegerField(default=0)),
                ('is_compute', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Single Page View',
                'verbose_name_plural': 'Single Page View',
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='Selian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_url', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dead Link',
                'verbose_name_plural': 'Dead Link',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Serializing'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('description', models.CharField(max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=99, help_text='Order of the top list page')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='SubjectImage')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Description of the tag SEO', max_length=240)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1)),
                ('star_num', models.CharField(choices=[('1', '1 Stars'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], default='3')),
                ('icon', models.CharField(blank=True, default='bi bi-pencil-square', max_length=50, null=True)),
                ('icon_color', models.CharField(choices=[('primary', 'Basic Blue'), ('success', 'Green'), ('info', 'Blue'), ('warning', 'Yellow'), ('danger', 'Red')], default='info', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField()),
                ('content', models.TextField(verbose_name='Principal content')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=99, help_text='Order of the top list page')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='blog.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topic',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('img_link', models.URLField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('is_top', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('topic_order', models.PositiveIntegerField(blank=True, default=99, null=True)),
                ('topic_short_title', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category')),
                ('keywords', models.ManyToManyField(to='blog.keyword', verbose_name='Articles keywords')),
                ('tags', models.ManyToManyField(to='blog.tag', verbose_name='Articles tags')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.topic')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
                'ordering': ['-create_date'],
            },
        ),
    ]
